export enum ProductTypes {
  VISA = "VISA",
  DOMESTIC_FLIGHT = "DOMESTIC_FLIGHT",
  INTERNATIONAL_FLIGHT = "INTERNATIONAL_FLIGHT",
  HOTEL = "HOTEL",
  RESIDENCY = "RESIDENCY",
  GROUP_TOUR = "GROUP_TOUR",
  INDIVIDUAL_TOUR = "INDIVIDUAL_TOUR",
}
