export enum OrderStatus {
  IN_PROGRESS = "IN_PROGRESS",
  FULFILLED = "FULFILLED",
  FAILED = "FAILED",
  PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
  UNKNOWN = "UNKNOWN",
}

export enum ResidencyOrderStatus {
  REQUESTED = "REQUESTED",
  IN_PROGRESS = "IN_PROGRESS",
  REJECTED = "REJECTED",
  CANCELED = "CANCELED",
  DONE = "DONE",
}

export enum VisaOrderStatus {
  REQUESTED = "REQUESTED",
  CONFIRMED = "CONFIRMED",
  PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PENDING_REFUND = "PENDING_REFUND",
  REFUNDED = "REFUNDED",
  IN_PROGRESS = "IN_PROGRESS",
  VISA_ISSUED = "VISA_ISSUED",
  DOCUMENTS_REJECTED = "DOCUMENTS_REJECTED",
  DOCUMENTS_ACCEPTED = "DOCUMENTS_ACCEPTED",
  REJECTED = "REJECTED",
}
